language: python
python:
    - "3.6.2"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
    - pip install pymysql
script:
    - py.test kinetics/test
after_success:
    - coveralls